-- MySQL Script generated by MySQL Workbench
-- 03/22/17 10:21:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Agências`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agências` (
  `idAgências` INT NOT NULL COMMENT '',
  `Nome da cidade` VARCHAR(45) NOT NULL COMMENT '',
  `Endereço` VARCHAR(45) NOT NULL COMMENT '',
  `Gerente` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAgências`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `idGerente` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(45) NOT NULL COMMENT '',
  `Email` VARCHAR(45) NOT NULL COMMENT '',
  `Agências_idAgências` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idGerente`)  COMMENT '',
  INDEX `fk_Gerente_Agências1_idx` (`Agências_idAgências` ASC)  COMMENT '',
  CONSTRAINT `fk_Gerente_Agências1`
    FOREIGN KEY (`Agências_idAgências`)
    REFERENCES `mydb`.`Agências` (`idAgências`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `idEquipamento` INT NOT NULL COMMENT '',
  `Modelo` VARCHAR(45) NOT NULL COMMENT '',
  `Marca` VARCHAR(45) NOT NULL COMMENT '',
  `Consumo` DECIMAL(10,0) NULL COMMENT '',
  PRIMARY KEY (`idEquipamento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suporte` (
  `idSuporte` INT NOT NULL COMMENT '',
  `Chamado` VARCHAR(45) NOT NULL COMMENT '',
  `Número protocolo` DECIMAL(10,0) NULL COMMENT '',
  PRIMARY KEY (`idSuporte`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCleinte` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(45) NOT NULL COMMENT '',
  `Endereço` VARCHAR(45) NOT NULL COMMENT '',
  `CPF` VARCHAR(45) NOT NULL COMMENT '',
  `Idade` INT(11) NULL COMMENT '',
  `Gerente_idGerente` INT NOT NULL COMMENT '',
  `Equipamento_idEquipamento` INT NOT NULL COMMENT '',
  `Suporte_idSuporte` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCleinte`)  COMMENT '',
  INDEX `fk_Cliente_Gerente_idx` (`Gerente_idGerente` ASC)  COMMENT '',
  INDEX `fk_Cliente_Equipamento1_idx` (`Equipamento_idEquipamento` ASC)  COMMENT '',
  INDEX `fk_Cliente_Suporte1_idx` (`Suporte_idSuporte` ASC)  COMMENT '',
  CONSTRAINT `fk_Cliente_Gerente`
    FOREIGN KEY (`Gerente_idGerente`)
    REFERENCES `mydb`.`Gerente` (`idGerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Suporte1`
    FOREIGN KEY (`Suporte_idSuporte`)
    REFERENCES `mydb`.`Suporte` (`idSuporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consumo` (
  `idConsumo` INT NOT NULL COMMENT '',
  `Horas` DECIMAL(10,0) NOT NULL COMMENT '',
  `Consumo` DECIMAL(10,0) NOT NULL COMMENT '',
  `Equipamento_idEquipamento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idConsumo`)  COMMENT '',
  INDEX `fk_Consumo_Equipamento1_idx` (`Equipamento_idEquipamento` ASC)  COMMENT '',
  CONSTRAINT `fk_Consumo_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
