-- MySQL Script generated by MySQL Workbench
-- Sat Apr  8 21:26:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT '',
  `address` VARCHAR(100) NULL DEFAULT '',
  `age` INT NULL DEFAULT 0,
  `cpf` VARCHAR(45) NULL DEFAULT '',
  `password` VARCHAR(17) NULL DEFAULT '',
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `password` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `idEquipment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `power` INT NOT NULL,
  `quantity` INT NOT NULL,
  `daily_usage` FLOAT NOT NULL,
  `Client_idClient` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idEquipment`),
  INDEX `fk_Equipment_Client1_idx` (`Client_idClient` ASC),
  CONSTRAINT `fk_Equipment_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agency` (
  `idAgency` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Manager_idClient` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idAgency`, `Manager_idClient`),
  INDEX `fk_Agency_Manager_idx` (`Manager_idClient` ASC),
  CONSTRAINT `fk_Agency_Manager`
    FOREIGN KEY (`Manager_idClient`)
    REFERENCES `mydb`.`Manager` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consumption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consumption` (
  `idConsumption` INT NOT NULL AUTO_INCREMENT,
  `current_day` DATE NOT NULL,
  `kwh_cost` FLOAT NOT NULL,
  `total_consumption` FLOAT NOT NULL,
  `daily_consumption` FLOAT NOT NULL,
  `monthly_consumption` FLOAT NOT NULL,
  PRIMARY KEY (`idConsumption`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Support` (
  `idSupport` INT NOT NULL AUTO_INCREMENT,
  `isAvailable` TINYINT NOT NULL,
  `protocol` VARCHAR(45) NOT NULL,
  `Manager_idClient` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idSupport`, `Manager_idClient`),
  INDEX `fk_Support_Manager1_idx` (`Manager_idClient` ASC),
  CONSTRAINT `fk_Support_Manager1`
    FOREIGN KEY (`Manager_idClient`)
    REFERENCES `mydb`.`Manager` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment_has_Consumption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment_has_Consumption` (
  `Equipment_idEquipment` INT NOT NULL DEFAULT 0,
  `Consumption_idConsumption` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Equipment_idEquipment`, `Consumption_idConsumption`),
  INDEX `fk_Equipment_has_Consumption_Consumption1_idx` (`Consumption_idConsumption` ASC),
  INDEX `fk_Equipment_has_Consumption_Equipment1_idx` (`Equipment_idEquipment` ASC),
  CONSTRAINT `fk_Equipment_has_Consumption_Equipment1`
    FOREIGN KEY (`Equipment_idEquipment`)
    REFERENCES `mydb`.`Equipment` (`idEquipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipment_has_Consumption_Consumption1`
    FOREIGN KEY (`Consumption_idConsumption`)
    REFERENCES `mydb`.`Consumption` (`idConsumption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
