# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(682, 464)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(451, 271))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 500))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8("font: 10pt"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(111, 161, 143);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab_crud = QtGui.QTabWidget(self.centralwidget)
        self.tab_crud.setGeometry(QtCore.QRect(10, 60, 661, 371))
        self.tab_crud.setStyleSheet(_fromUtf8("background-color: rgb(111, 161, 143);"))
        self.tab_crud.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_crud.setObjectName(_fromUtf8("tab_crud"))
        self.client_tab = QtGui.QWidget()
        self.client_tab.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.client_tab.setObjectName(_fromUtf8("client_tab"))
        self.client_table = QtGui.QTableWidget(self.client_tab)
        self.client_table.setGeometry(QtCore.QRect(20, 80, 561, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_table.sizePolicy().hasHeightForWidth())
        self.client_table.setSizePolicy(sizePolicy)
        self.client_table.setAutoFillBackground(False)
        self.client_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.client_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.client_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.client_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.client_table.setAlternatingRowColors(False)
        self.client_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.client_table.setWordWrap(True)
        self.client_table.setObjectName(_fromUtf8("client_table"))
        self.client_table.setColumnCount(4)
        self.client_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.client_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.client_table.setItem(0, 3, item)
        self.client_table.horizontalHeader().setCascadingSectionResizes(True)
        self.client_table.verticalHeader().setVisible(False)
        self.gridLayoutWidget = QtGui.QWidget(self.client_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 0, 561, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.client_input_address = QtGui.QLineEdit(self.gridLayoutWidget)
        self.client_input_address.setObjectName(_fromUtf8("client_input_address"))
        self.gridLayout_2.addWidget(self.client_input_address, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.client_lbl_address = QtGui.QLabel(self.gridLayoutWidget)
        self.client_lbl_address.setObjectName(_fromUtf8("client_lbl_address"))
        self.gridLayout_2.addWidget(self.client_lbl_address, 0, 4, 1, 1)
        self.client_input_cpf = QtGui.QLineEdit(self.gridLayoutWidget)
        self.client_input_cpf.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.client_input_cpf.setObjectName(_fromUtf8("client_input_cpf"))
        self.gridLayout_2.addWidget(self.client_input_cpf, 1, 5, 1, 1)
        self.client_input_name = QtGui.QLineEdit(self.gridLayoutWidget)
        self.client_input_name.setObjectName(_fromUtf8("client_input_name"))
        self.gridLayout_2.addWidget(self.client_input_name, 0, 2, 1, 1)
        self.client_lbl_cpf = QtGui.QLabel(self.gridLayoutWidget)
        self.client_lbl_cpf.setObjectName(_fromUtf8("client_lbl_cpf"))
        self.gridLayout_2.addWidget(self.client_lbl_cpf, 1, 4, 1, 1)
        self.client_lbl_name = QtGui.QLabel(self.gridLayoutWidget)
        self.client_lbl_name.setObjectName(_fromUtf8("client_lbl_name"))
        self.gridLayout_2.addWidget(self.client_lbl_name, 0, 0, 1, 1)
        self.client_lbl_age = QtGui.QLabel(self.gridLayoutWidget)
        self.client_lbl_age.setObjectName(_fromUtf8("client_lbl_age"))
        self.gridLayout_2.addWidget(self.client_lbl_age, 1, 0, 1, 1)
        self.client_input_age = QtGui.QSpinBox(self.gridLayoutWidget)
        self.client_input_age.setMaximum(130)
        self.client_input_age.setObjectName(_fromUtf8("client_input_age"))
        self.gridLayout_2.addWidget(self.client_input_age, 1, 2, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(self.client_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(590, 20, 51, 271))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.client_btn_create = QtGui.QPushButton(self.verticalLayoutWidget)
        self.client_btn_create.setMinimumSize(QtCore.QSize(41, 41))
        self.client_btn_create.setMaximumSize(QtCore.QSize(41, 41))
        self.client_btn_create.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_btn_create.setIcon(icon)
        self.client_btn_create.setIconSize(QtCore.QSize(32, 32))
        self.client_btn_create.setFlat(True)
        self.client_btn_create.setObjectName(_fromUtf8("client_btn_create"))
        self.verticalLayout.addWidget(self.client_btn_create)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.client_btn_edit = QtGui.QPushButton(self.verticalLayoutWidget)
        self.client_btn_edit.setMinimumSize(QtCore.QSize(41, 41))
        self.client_btn_edit.setMaximumSize(QtCore.QSize(41, 41))
        self.client_btn_edit.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_btn_edit.setIcon(icon1)
        self.client_btn_edit.setIconSize(QtCore.QSize(32, 32))
        self.client_btn_edit.setFlat(True)
        self.client_btn_edit.setObjectName(_fromUtf8("client_btn_edit"))
        self.verticalLayout.addWidget(self.client_btn_edit)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.client_btn_pdf = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_btn_pdf.sizePolicy().hasHeightForWidth())
        self.client_btn_pdf.setSizePolicy(sizePolicy)
        self.client_btn_pdf.setMinimumSize(QtCore.QSize(41, 41))
        self.client_btn_pdf.setMaximumSize(QtCore.QSize(41, 41))
        self.client_btn_pdf.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_btn_pdf.setIcon(icon2)
        self.client_btn_pdf.setIconSize(QtCore.QSize(32, 32))
        self.client_btn_pdf.setFlat(True)
        self.client_btn_pdf.setObjectName(_fromUtf8("client_btn_pdf"))
        self.verticalLayout.addWidget(self.client_btn_pdf)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.client_btn_delete = QtGui.QPushButton(self.verticalLayoutWidget)
        self.client_btn_delete.setMinimumSize(QtCore.QSize(41, 41))
        self.client_btn_delete.setMaximumSize(QtCore.QSize(41, 41))
        self.client_btn_delete.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_btn_delete.setIcon(icon3)
        self.client_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.client_btn_delete.setFlat(True)
        self.client_btn_delete.setObjectName(_fromUtf8("client_btn_delete"))
        self.verticalLayout.addWidget(self.client_btn_delete)
        self.horizontalLayoutWidget = QtGui.QWidget(self.client_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 300, 601, 43))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.client_lbl_search = QtGui.QLabel(self.horizontalLayoutWidget)
        self.client_lbl_search.setObjectName(_fromUtf8("client_lbl_search"))
        self.horizontalLayout.addWidget(self.client_lbl_search)
        self.client_cb_search = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.client_cb_search.setMinimumSize(QtCore.QSize(110, 0))
        self.client_cb_search.setObjectName(_fromUtf8("client_cb_search"))
        self.client_cb_search.addItem(_fromUtf8(""))
        self.client_cb_search.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.client_cb_search)
        self.client_input_search = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.client_input_search.setObjectName(_fromUtf8("client_input_search"))
        self.horizontalLayout.addWidget(self.client_input_search)
        spacerItem4 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.client_btn_search = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.client_btn_search.setMinimumSize(QtCore.QSize(26, 26))
        self.client_btn_search.setMaximumSize(QtCore.QSize(26, 26))
        self.client_btn_search.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/magnification-lens.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_btn_search.setIcon(icon4)
        self.client_btn_search.setIconSize(QtCore.QSize(20, 20))
        self.client_btn_search.setFlat(True)
        self.client_btn_search.setObjectName(_fromUtf8("client_btn_search"))
        self.horizontalLayout.addWidget(self.client_btn_search)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.client_table.raise_()
        self.gridLayoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.client_btn_pdf.raise_()
        self.client_btn_edit.raise_()
        self.client_btn_delete.raise_()
        self.tab_crud.addTab(self.client_tab, _fromUtf8(""))
        self.equipment_tab = QtGui.QWidget()
        self.equipment_tab.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.equipment_tab.setObjectName(_fromUtf8("equipment_tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.equipment_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 561, 61))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.equipment_lbl_power = QtGui.QLabel(self.gridLayoutWidget_2)
        self.equipment_lbl_power.setObjectName(_fromUtf8("equipment_lbl_power"))
        self.gridLayout_4.addWidget(self.equipment_lbl_power, 0, 3, 1, 1)
        self.equipment_lbl_name = QtGui.QLabel(self.gridLayoutWidget_2)
        self.equipment_lbl_name.setObjectName(_fromUtf8("equipment_lbl_name"))
        self.gridLayout_4.addWidget(self.equipment_lbl_name, 0, 1, 1, 1)
        self.equipment_input_name = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.equipment_input_name.setObjectName(_fromUtf8("equipment_input_name"))
        self.gridLayout_4.addWidget(self.equipment_input_name, 0, 2, 1, 1)
        self.equipment_input_power = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.equipment_input_power.setMinimumSize(QtCore.QSize(150, 0))
        self.equipment_input_power.setMaximum(100000)
        self.equipment_input_power.setObjectName(_fromUtf8("equipment_input_power"))
        self.gridLayout_4.addWidget(self.equipment_input_power, 0, 4, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.equipment_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(590, 20, 51, 271))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.equipment_btn_create = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.equipment_btn_create.setMinimumSize(QtCore.QSize(41, 41))
        self.equipment_btn_create.setMaximumSize(QtCore.QSize(41, 41))
        self.equipment_btn_create.setText(_fromUtf8(""))
        self.equipment_btn_create.setIcon(icon)
        self.equipment_btn_create.setIconSize(QtCore.QSize(32, 32))
        self.equipment_btn_create.setFlat(True)
        self.equipment_btn_create.setObjectName(_fromUtf8("equipment_btn_create"))
        self.verticalLayout_2.addWidget(self.equipment_btn_create)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.equipment_btn_update = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.equipment_btn_update.setMinimumSize(QtCore.QSize(41, 41))
        self.equipment_btn_update.setMaximumSize(QtCore.QSize(41, 41))
        self.equipment_btn_update.setText(_fromUtf8(""))
        self.equipment_btn_update.setIcon(icon1)
        self.equipment_btn_update.setIconSize(QtCore.QSize(32, 32))
        self.equipment_btn_update.setFlat(True)
        self.equipment_btn_update.setObjectName(_fromUtf8("equipment_btn_update"))
        self.verticalLayout_2.addWidget(self.equipment_btn_update)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.equipment_btn_pdf = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equipment_btn_pdf.sizePolicy().hasHeightForWidth())
        self.equipment_btn_pdf.setSizePolicy(sizePolicy)
        self.equipment_btn_pdf.setMinimumSize(QtCore.QSize(41, 41))
        self.equipment_btn_pdf.setMaximumSize(QtCore.QSize(41, 41))
        self.equipment_btn_pdf.setText(_fromUtf8(""))
        self.equipment_btn_pdf.setIcon(icon2)
        self.equipment_btn_pdf.setIconSize(QtCore.QSize(32, 32))
        self.equipment_btn_pdf.setFlat(True)
        self.equipment_btn_pdf.setObjectName(_fromUtf8("equipment_btn_pdf"))
        self.verticalLayout_2.addWidget(self.equipment_btn_pdf)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.equipment_btn_delete = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.equipment_btn_delete.setMinimumSize(QtCore.QSize(41, 41))
        self.equipment_btn_delete.setMaximumSize(QtCore.QSize(41, 41))
        self.equipment_btn_delete.setText(_fromUtf8(""))
        self.equipment_btn_delete.setIcon(icon3)
        self.equipment_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.equipment_btn_delete.setFlat(True)
        self.equipment_btn_delete.setObjectName(_fromUtf8("equipment_btn_delete"))
        self.verticalLayout_2.addWidget(self.equipment_btn_delete)
        self.equipment_table = QtGui.QTableWidget(self.equipment_tab)
        self.equipment_table.setGeometry(QtCore.QRect(20, 80, 561, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equipment_table.sizePolicy().hasHeightForWidth())
        self.equipment_table.setSizePolicy(sizePolicy)
        self.equipment_table.setAutoFillBackground(False)
        self.equipment_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.equipment_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.equipment_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.equipment_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.equipment_table.setAlternatingRowColors(False)
        self.equipment_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.equipment_table.setWordWrap(True)
        self.equipment_table.setObjectName(_fromUtf8("equipment_table"))
        self.equipment_table.setColumnCount(4)
        self.equipment_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_table.setItem(0, 3, item)
        self.equipment_table.horizontalHeader().setCascadingSectionResizes(True)
        self.equipment_table.verticalHeader().setVisible(False)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.equipment_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 300, 601, 43))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.equipment_lbl_search = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.equipment_lbl_search.setObjectName(_fromUtf8("equipment_lbl_search"))
        self.horizontalLayout_2.addWidget(self.equipment_lbl_search)
        self.equipment_cb_search = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.equipment_cb_search.setMinimumSize(QtCore.QSize(110, 0))
        self.equipment_cb_search.setObjectName(_fromUtf8("equipment_cb_search"))
        self.equipment_cb_search.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.equipment_cb_search)
        self.equipment_input_search = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.equipment_input_search.setObjectName(_fromUtf8("equipment_input_search"))
        self.horizontalLayout_2.addWidget(self.equipment_input_search)
        spacerItem9 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.equipment_btn_search = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.equipment_btn_search.setMinimumSize(QtCore.QSize(26, 26))
        self.equipment_btn_search.setMaximumSize(QtCore.QSize(26, 26))
        self.equipment_btn_search.setText(_fromUtf8(""))
        self.equipment_btn_search.setIcon(icon4)
        self.equipment_btn_search.setIconSize(QtCore.QSize(20, 20))
        self.equipment_btn_search.setFlat(True)
        self.equipment_btn_search.setObjectName(_fromUtf8("equipment_btn_search"))
        self.horizontalLayout_2.addWidget(self.equipment_btn_search)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.tab_crud.addTab(self.equipment_tab, _fromUtf8(""))
        self.btn_home = QtGui.QPushButton(self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("view/img/logo-cemig.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon5)
        self.btn_home.setIconSize(QtCore.QSize(141, 41))
        self.btn_home.setFlat(True)
        self.btn_home.setObjectName(_fromUtf8("btn_home"))
        self.home_widget = QtGui.QWidget(self.centralwidget)
        self.home_widget.setGeometry(QtCore.QRect(10, 50, 661, 361))
        self.home_widget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.home_widget.setObjectName(_fromUtf8("home_widget"))
        self.home_table = QtGui.QTableWidget(self.home_widget)
        self.home_table.setGeometry(QtCore.QRect(10, 50, 641, 231))
        self.home_table.setShowGrid(True)
        self.home_table.setGridStyle(QtCore.Qt.SolidLine)
        self.home_table.setObjectName(_fromUtf8("home_table"))
        self.home_table.setColumnCount(6)
        self.home_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.home_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.home_table.setItem(0, 5, item)
        self.home_table.horizontalHeader().setCascadingSectionResizes(True)
        self.home_table.horizontalHeader().setDefaultSectionSize(90)
        self.home_table.horizontalHeader().setMinimumSectionSize(20)
        self.home_table.horizontalHeader().setSortIndicatorShown(True)
        self.home_table.horizontalHeader().setStretchLastSection(True)
        self.home_table.verticalHeader().setDefaultSectionSize(30)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.home_widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 282, 611, 73))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.client_btn_create_2 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.client_btn_create_2.setMinimumSize(QtCore.QSize(26, 26))
        self.client_btn_create_2.setMaximumSize(QtCore.QSize(26, 26))
        self.client_btn_create_2.setText(_fromUtf8(""))
        self.client_btn_create_2.setIcon(icon)
        self.client_btn_create_2.setIconSize(QtCore.QSize(20, 20))
        self.client_btn_create_2.setFlat(True)
        self.client_btn_create_2.setObjectName(_fromUtf8("client_btn_create_2"))
        self.gridLayout_3.addWidget(self.client_btn_create_2, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.equipment_cb_search_2 = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.equipment_cb_search_2.setMinimumSize(QtCore.QSize(150, 30))
        self.equipment_cb_search_2.setMaximumSize(QtCore.QSize(150, 30))
        self.equipment_cb_search_2.setObjectName(_fromUtf8("equipment_cb_search_2"))
        self.equipment_cb_search_2.addItem(_fromUtf8(""))
        self.equipment_cb_search_2.addItem(_fromUtf8(""))
        self.equipment_cb_search_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.equipment_cb_search_2, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.home_btn_generate_report = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_generate_report.sizePolicy().hasHeightForWidth())
        self.home_btn_generate_report.setSizePolicy(sizePolicy)
        self.home_btn_generate_report.setMaximumSize(QtCore.QSize(50000, 30))
        self.home_btn_generate_report.setBaseSize(QtCore.QSize(0, 0))
        self.home_btn_generate_report.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.home_btn_generate_report.setIconSize(QtCore.QSize(32, 32))
        self.home_btn_generate_report.setFlat(False)
        self.home_btn_generate_report.setObjectName(_fromUtf8("home_btn_generate_report"))
        self.horizontalLayout_3.addWidget(self.home_btn_generate_report)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.home_lbl_total_waste = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.home_lbl_total_waste.setObjectName(_fromUtf8("home_lbl_total_waste"))
        self.horizontalLayout_3.addWidget(self.home_lbl_total_waste)
        self.home_input_total = QtGui.QLCDNumber(self.horizontalLayoutWidget_3)
        self.home_input_total.setMaximumSize(QtCore.QSize(16777215, 30))
        self.home_input_total.setObjectName(_fromUtf8("home_input_total"))
        self.horizontalLayout_3.addWidget(self.home_input_total)
        self.home_lbl_total_waste_unit = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.home_lbl_total_waste_unit.setObjectName(_fromUtf8("home_lbl_total_waste_unit"))
        self.horizontalLayout_3.addWidget(self.home_lbl_total_waste_unit)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.home_widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(-10, -10, 681, 48))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.home_lbl_title = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.home_lbl_title.setFont(font)
        self.home_lbl_title.setStyleSheet(_fromUtf8("background-color: rgb(111, 161, 143);"))
        self.home_lbl_title.setObjectName(_fromUtf8("home_lbl_title"))
        self.horizontalLayout_4.addWidget(self.home_lbl_title)
        self.home_table.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.home_btn_generate_report.raise_()
        self.login_widget = QtGui.QWidget(self.centralwidget)
        self.login_widget.setGeometry(QtCore.QRect(140, 110, 411, 191))
        self.login_widget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.login_widget.setObjectName(_fromUtf8("login_widget"))
        self.gridLayout = QtGui.QGridLayout(self.login_widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 2, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 1, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 1, 2, 1, 1)
        self.button_layout_login = QtGui.QHBoxLayout()
        self.button_layout_login.setObjectName(_fromUtf8("button_layout_login"))
        self.login_btn_register = QtGui.QPushButton(self.login_widget)
        self.login_btn_register.setObjectName(_fromUtf8("login_btn_register"))
        self.button_layout_login.addWidget(self.login_btn_register)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.button_layout_login.addItem(spacerItem17)
        self.login_btn_login = QtGui.QPushButton(self.login_widget)
        self.login_btn_login.setObjectName(_fromUtf8("login_btn_login"))
        self.button_layout_login.addWidget(self.login_btn_login)
        self.gridLayout.addLayout(self.button_layout_login, 3, 0, 1, 3)
        self.form_layout_login = QtGui.QFormLayout()
        self.form_layout_login.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.form_layout_login.setObjectName(_fromUtf8("form_layout_login"))
        self.login_lbl_cpf = QtGui.QLabel(self.login_widget)
        self.login_lbl_cpf.setObjectName(_fromUtf8("login_lbl_cpf"))
        self.form_layout_login.setWidget(0, QtGui.QFormLayout.LabelRole, self.login_lbl_cpf)
        self.login_input_cpf = QtGui.QLineEdit(self.login_widget)
        self.login_input_cpf.setMinimumSize(QtCore.QSize(133, 0))
        self.login_input_cpf.setMaxLength(14)
        self.login_input_cpf.setPlaceholderText(_fromUtf8(""))
        self.login_input_cpf.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.login_input_cpf.setObjectName(_fromUtf8("login_input_cpf"))
        self.form_layout_login.setWidget(0, QtGui.QFormLayout.FieldRole, self.login_input_cpf)
        self.login_lbl_password = QtGui.QLabel(self.login_widget)
        self.login_lbl_password.setObjectName(_fromUtf8("login_lbl_password"))
        self.form_layout_login.setWidget(1, QtGui.QFormLayout.LabelRole, self.login_lbl_password)
        self.login_input_password = QtGui.QLineEdit(self.login_widget)
        self.login_input_password.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.login_input_password.setInputMask(_fromUtf8(""))
        self.login_input_password.setText(_fromUtf8(""))
        self.login_input_password.setMaxLength(16)
        self.login_input_password.setEchoMode(QtGui.QLineEdit.Password)
        self.login_input_password.setPlaceholderText(_fromUtf8(""))
        self.login_input_password.setObjectName(_fromUtf8("login_input_password"))
        self.form_layout_login.setWidget(1, QtGui.QFormLayout.FieldRole, self.login_input_password)
        self.gridLayout.addLayout(self.form_layout_login, 1, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 0, 1, 1, 1)
        self.btn_home.raise_()
        self.home_btn_generate_report.raise_()
        self.tab_crud.raise_()
        self.home_widget.raise_()
        self.login_widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setGeometry(QtCore.QRect(326, 135, 155, 94))
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_settings = QtGui.QMenu(self.menubar)
        self.menu_settings.setObjectName(_fromUtf8("menu_settings"))
        MainWindow.setMenuBar(self.menubar)
        self.actionHome = QtGui.QAction(MainWindow)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_help_about = QtGui.QAction(MainWindow)
        self.menu_help_about.setMenuRole(QtGui.QAction.AboutRole)
        self.menu_help_about.setObjectName(_fromUtf8("menu_help_about"))
        self.menu_file_new_client = QtGui.QAction(MainWindow)
        self.menu_file_new_client.setObjectName(_fromUtf8("menu_file_new_client"))
        self.menu_file_new_manager = QtGui.QAction(MainWindow)
        self.menu_file_new_manager.setObjectName(_fromUtf8("menu_file_new_manager"))
        self.menu_file_new_equipment = QtGui.QAction(MainWindow)
        self.menu_file_new_equipment.setObjectName(_fromUtf8("menu_file_new_equipment"))
        self.menu_file_new_agency = QtGui.QAction(MainWindow)
        self.menu_file_new_agency.setObjectName(_fromUtf8("menu_file_new_agency"))
        self.menu_file_new_support = QtGui.QAction(MainWindow)
        self.menu_file_new_support.setObjectName(_fromUtf8("menu_file_new_support"))
        self.menu_file_new_consumption = QtGui.QAction(MainWindow)
        self.menu_file_new_consumption.setObjectName(_fromUtf8("menu_file_new_consumption"))
        self.menu_file_import = QtGui.QAction(MainWindow)
        self.menu_file_import.setObjectName(_fromUtf8("menu_file_import"))
        self.menu_file_export = QtGui.QAction(MainWindow)
        self.menu_file_export.setObjectName(_fromUtf8("menu_file_export"))
        self.menu_file_logout = QtGui.QAction(MainWindow)
        self.menu_file_logout.setObjectName(_fromUtf8("menu_file_logout"))
        self.menu_file_generate = QtGui.QAction(MainWindow)
        self.menu_file_generate.setObjectName(_fromUtf8("menu_file_generate"))
        self.menu_file_quit = QtGui.QAction(MainWindow)
        self.menu_file_quit.setObjectName(_fromUtf8("menu_file_quit"))
        self.menu_edit_search_client = QtGui.QAction(MainWindow)
        self.menu_edit_search_client.setObjectName(_fromUtf8("menu_edit_search_client"))
        self.menu_edit_search_manager = QtGui.QAction(MainWindow)
        self.menu_edit_search_manager.setObjectName(_fromUtf8("menu_edit_search_manager"))
        self.menu_edit_search_equipment = QtGui.QAction(MainWindow)
        self.menu_edit_search_equipment.setObjectName(_fromUtf8("menu_edit_search_equipment"))
        self.menu_edit_search_agency = QtGui.QAction(MainWindow)
        self.menu_edit_search_agency.setObjectName(_fromUtf8("menu_edit_search_agency"))
        self.menu_edit_search_consumption = QtGui.QAction(MainWindow)
        self.menu_edit_search_consumption.setObjectName(_fromUtf8("menu_edit_search_consumption"))
        self.menu_edit_search_support = QtGui.QAction(MainWindow)
        self.menu_edit_search_support.setObjectName(_fromUtf8("menu_edit_search_support"))
        self.menu_edit_search_all = QtGui.QAction(MainWindow)
        self.menu_edit_search_all.setObjectName(_fromUtf8("menu_edit_search_all"))
        self.menu_edit_update_client = QtGui.QAction(MainWindow)
        self.menu_edit_update_client.setObjectName(_fromUtf8("menu_edit_update_client"))
        self.menu_edit_update_manager = QtGui.QAction(MainWindow)
        self.menu_edit_update_manager.setObjectName(_fromUtf8("menu_edit_update_manager"))
        self.menu_edit_update_equipment = QtGui.QAction(MainWindow)
        self.menu_edit_update_equipment.setObjectName(_fromUtf8("menu_edit_update_equipment"))
        self.menu_edit_update_agency = QtGui.QAction(MainWindow)
        self.menu_edit_update_agency.setObjectName(_fromUtf8("menu_edit_update_agency"))
        self.menu_edit_update_consumption = QtGui.QAction(MainWindow)
        self.menu_edit_update_consumption.setObjectName(_fromUtf8("menu_edit_update_consumption"))
        self.menu_edit_update_support = QtGui.QAction(MainWindow)
        self.menu_edit_update_support.setObjectName(_fromUtf8("menu_edit_update_support"))
        self.menu_edit_update_all = QtGui.QAction(MainWindow)
        self.menu_edit_update_all.setObjectName(_fromUtf8("menu_edit_update_all"))
        self.menu_edit_list_client = QtGui.QAction(MainWindow)
        self.menu_edit_list_client.setObjectName(_fromUtf8("menu_edit_list_client"))
        self.menu_edit_list_manager = QtGui.QAction(MainWindow)
        self.menu_edit_list_manager.setObjectName(_fromUtf8("menu_edit_list_manager"))
        self.menu_edit_list_equipment = QtGui.QAction(MainWindow)
        self.menu_edit_list_equipment.setObjectName(_fromUtf8("menu_edit_list_equipment"))
        self.menu_edit_list_agency = QtGui.QAction(MainWindow)
        self.menu_edit_list_agency.setObjectName(_fromUtf8("menu_edit_list_agency"))
        self.menu_edit_list_consumption = QtGui.QAction(MainWindow)
        self.menu_edit_list_consumption.setObjectName(_fromUtf8("menu_edit_list_consumption"))
        self.menu_edit_list_support = QtGui.QAction(MainWindow)
        self.menu_edit_list_support.setObjectName(_fromUtf8("menu_edit_list_support"))
        self.menu_edit_list_all = QtGui.QAction(MainWindow)
        self.menu_edit_list_all.setObjectName(_fromUtf8("menu_edit_list_all"))
        self.menu_edit_remove_client = QtGui.QAction(MainWindow)
        self.menu_edit_remove_client.setObjectName(_fromUtf8("menu_edit_remove_client"))
        self.menu_edit_remove_manager = QtGui.QAction(MainWindow)
        self.menu_edit_remove_manager.setObjectName(_fromUtf8("menu_edit_remove_manager"))
        self.menu_edit_remove_equipment = QtGui.QAction(MainWindow)
        self.menu_edit_remove_equipment.setObjectName(_fromUtf8("menu_edit_remove_equipment"))
        self.menu_edit_remove_agency = QtGui.QAction(MainWindow)
        self.menu_edit_remove_agency.setObjectName(_fromUtf8("menu_edit_remove_agency"))
        self.menu_edit_remove_consumption = QtGui.QAction(MainWindow)
        self.menu_edit_remove_consumption.setObjectName(_fromUtf8("menu_edit_remove_consumption"))
        self.menu_edit_remove_support = QtGui.QAction(MainWindow)
        self.menu_edit_remove_support.setObjectName(_fromUtf8("menu_edit_remove_support"))
        self.menu_edit_remove_all = QtGui.QAction(MainWindow)
        self.menu_edit_remove_all.setObjectName(_fromUtf8("menu_edit_remove_all"))
        self.menu_help_contact = QtGui.QAction(MainWindow)
        self.menu_help_contact.setObjectName(_fromUtf8("menu_help_contact"))
        self.menu_settings_manage = QtGui.QAction(MainWindow)
        self.menu_settings_manage.setObjectName(_fromUtf8("menu_settings_manage"))
        self.menu_file.addAction(self.menu_file_logout)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_file_quit)
        self.menu_help.addAction(self.menu_help_about)
        self.menu_help.addAction(self.menu_help_contact)
        self.menu_settings.addAction(self.menu_settings_manage)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_crud.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.client_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.client_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.client_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Age", None))
        item = self.client_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.client_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CPF", None))
        __sortingEnabled = self.client_table.isSortingEnabled()
        self.client_table.setSortingEnabled(False)
        item = self.client_table.item(0, 0)
        item.setText(_translate("MainWindow", "Pedro", None))
        item = self.client_table.item(0, 1)
        item.setText(_translate("MainWindow", "20", None))
        item = self.client_table.item(0, 2)
        item.setText(_translate("MainWindow", "Rua José Mendes da Silva", None))
        item = self.client_table.item(0, 3)
        item.setText(_translate("MainWindow", "08296082659", None))
        self.client_table.setSortingEnabled(__sortingEnabled)
        self.client_lbl_address.setText(_translate("MainWindow", "Address:", None))
        self.client_input_cpf.setInputMask(_translate("MainWindow", "999.999.999-99; ", None))
        self.client_lbl_cpf.setText(_translate("MainWindow", "CPF:", None))
        self.client_lbl_name.setText(_translate("MainWindow", "Name:", None))
        self.client_lbl_age.setText(_translate("MainWindow", "Age:", None))
        self.client_btn_create.setToolTip(_translate("MainWindow", "Submit ", None))
        self.client_btn_edit.setToolTip(_translate("MainWindow", "Edit selected  ", None))
        self.client_btn_pdf.setToolTip(_translate("MainWindow", "Export to .pdf   ", None))
        self.client_btn_delete.setToolTip(_translate("MainWindow", "Delete selected   ", None))
        self.client_lbl_search.setText(_translate("MainWindow", "Search:", None))
        self.client_cb_search.setItemText(0, _translate("MainWindow", "Name", None))
        self.client_cb_search.setItemText(1, _translate("MainWindow", "CPF", None))
        self.tab_crud.setTabText(self.tab_crud.indexOf(self.client_tab), _translate("MainWindow", "Client", None))
        self.equipment_lbl_power.setText(_translate("MainWindow", "Power [W]:", None))
        self.equipment_lbl_name.setText(_translate("MainWindow", "Name:", None))
        self.equipment_btn_create.setToolTip(_translate("MainWindow", "Submit ", None))
        self.equipment_btn_update.setToolTip(_translate("MainWindow", "Edit Selected  ", None))
        self.equipment_btn_pdf.setToolTip(_translate("MainWindow", "Export to .pdf   ", None))
        self.equipment_btn_delete.setToolTip(_translate("MainWindow", "Delete selected   ", None))
        item = self.equipment_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.equipment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.equipment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Power [W]", None))
        item = self.equipment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Average Consumption [kWh/day]", None))
        item = self.equipment_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Average Cost [R$/day]", None))
        __sortingEnabled = self.equipment_table.isSortingEnabled()
        self.equipment_table.setSortingEnabled(False)
        item = self.equipment_table.item(0, 0)
        item.setText(_translate("MainWindow", "TV", None))
        item = self.equipment_table.item(0, 1)
        item.setText(_translate("MainWindow", "20", None))
        item = self.equipment_table.item(0, 2)
        item.setText(_translate("MainWindow", "30", None))
        item = self.equipment_table.item(0, 3)
        item.setText(_translate("MainWindow", "R$ 3,00", None))
        self.equipment_table.setSortingEnabled(__sortingEnabled)
        self.equipment_lbl_search.setText(_translate("MainWindow", "Search:", None))
        self.equipment_cb_search.setItemText(0, _translate("MainWindow", "Name", None))
        self.tab_crud.setTabText(self.tab_crud.indexOf(self.equipment_tab), _translate("MainWindow", "Equipment", None))
        item = self.home_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.home_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Equipment", None))
        item = self.home_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quant.", None))
        item = self.home_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pot [W]", None))
        item = self.home_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Daily Usage [h]", None))
        item = self.home_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Month\'s Day", None))
        item = self.home_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Consumption [kWh/month]", None))
        __sortingEnabled = self.home_table.isSortingEnabled()
        self.home_table.setSortingEnabled(False)
        item = self.home_table.item(0, 0)
        item.setText(_translate("MainWindow", "TV", None))
        item = self.home_table.item(0, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.home_table.item(0, 2)
        item.setText(_translate("MainWindow", "50", None))
        item = self.home_table.item(0, 3)
        item.setText(_translate("MainWindow", "2", None))
        item = self.home_table.item(0, 4)
        item.setText(_translate("MainWindow", "10", None))
        item = self.home_table.item(0, 5)
        item.setText(_translate("MainWindow", "--result--", None))
        self.home_table.setSortingEnabled(__sortingEnabled)
        self.client_btn_create_2.setToolTip(_translate("MainWindow", "Submit ", None))
        self.label.setText(_translate("MainWindow", "Add equipment:", None))
        self.equipment_cb_search_2.setItemText(0, _translate("MainWindow", "TV", None))
        self.equipment_cb_search_2.setItemText(1, _translate("MainWindow", "Air Conditioner", None))
        self.equipment_cb_search_2.setItemText(2, _translate("MainWindow", "Electric Shower", None))
        self.home_btn_generate_report.setText(_translate("MainWindow", "Generate report", None))
        self.home_lbl_total_waste.setText(_translate("MainWindow", "Total waste:", None))
        self.home_lbl_total_waste_unit.setText(_translate("MainWindow", "kWh/month", None))
        self.home_lbl_title.setText(_translate("MainWindow", "Energy Consumption Calculator", None))
        self.login_btn_register.setText(_translate("MainWindow", "Register", None))
        self.login_btn_login.setText(_translate("MainWindow", "Login", None))
        self.login_lbl_cpf.setText(_translate("MainWindow", "CPF:", None))
        self.login_input_cpf.setInputMask(_translate("MainWindow", "999.999.999-99; ", None))
        self.login_input_cpf.setText(_translate("MainWindow", "..-", None))
        self.login_lbl_password.setText(_translate("MainWindow", "Password:", None))
        self.menu_file.setTitle(_translate("MainWindow", "File", None))
        self.menu_help.setTitle(_translate("MainWindow", "Help", None))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionHome.setText(_translate("MainWindow", "Home", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.menu_help_about.setText(_translate("MainWindow", "About", None))
        self.menu_file_new_client.setText(_translate("MainWindow", "Client", None))
        self.menu_file_new_manager.setText(_translate("MainWindow", "Manager", None))
        self.menu_file_new_equipment.setText(_translate("MainWindow", "Equipment", None))
        self.menu_file_new_agency.setText(_translate("MainWindow", "Agency", None))
        self.menu_file_new_support.setText(_translate("MainWindow", "Support", None))
        self.menu_file_new_consumption.setText(_translate("MainWindow", "Consumption", None))
        self.menu_file_import.setText(_translate("MainWindow", "Import", None))
        self.menu_file_export.setText(_translate("MainWindow", "Export", None))
        self.menu_file_logout.setText(_translate("MainWindow", "Log out", None))
        self.menu_file_generate.setText(_translate("MainWindow", "Generate report (.pdf)", None))
        self.menu_file_quit.setText(_translate("MainWindow", "Quit", None))
        self.menu_file_quit.setToolTip(_translate("MainWindow", "Quit", None))
        self.menu_edit_search_client.setText(_translate("MainWindow", "Client", None))
        self.menu_edit_search_manager.setText(_translate("MainWindow", "Manager", None))
        self.menu_edit_search_equipment.setText(_translate("MainWindow", "Equipment", None))
        self.menu_edit_search_agency.setText(_translate("MainWindow", "Agency", None))
        self.menu_edit_search_consumption.setText(_translate("MainWindow", "Consumption", None))
        self.menu_edit_search_support.setText(_translate("MainWindow", "Support", None))
        self.menu_edit_search_all.setText(_translate("MainWindow", "All", None))
        self.menu_edit_update_client.setText(_translate("MainWindow", "Client", None))
        self.menu_edit_update_manager.setText(_translate("MainWindow", "Manager", None))
        self.menu_edit_update_equipment.setText(_translate("MainWindow", "Equipment", None))
        self.menu_edit_update_agency.setText(_translate("MainWindow", "Agency", None))
        self.menu_edit_update_consumption.setText(_translate("MainWindow", "Consumption", None))
        self.menu_edit_update_support.setText(_translate("MainWindow", "Support", None))
        self.menu_edit_update_all.setText(_translate("MainWindow", "All", None))
        self.menu_edit_list_client.setText(_translate("MainWindow", "Client", None))
        self.menu_edit_list_manager.setText(_translate("MainWindow", "Manager", None))
        self.menu_edit_list_equipment.setText(_translate("MainWindow", "Equipment", None))
        self.menu_edit_list_agency.setText(_translate("MainWindow", "Agency", None))
        self.menu_edit_list_consumption.setText(_translate("MainWindow", "Consumption", None))
        self.menu_edit_list_support.setText(_translate("MainWindow", "Support", None))
        self.menu_edit_list_all.setText(_translate("MainWindow", "All", None))
        self.menu_edit_remove_client.setText(_translate("MainWindow", "Client", None))
        self.menu_edit_remove_manager.setText(_translate("MainWindow", "Manager", None))
        self.menu_edit_remove_equipment.setText(_translate("MainWindow", "Equipment", None))
        self.menu_edit_remove_agency.setText(_translate("MainWindow", "Agency", None))
        self.menu_edit_remove_consumption.setText(_translate("MainWindow", "Consumption", None))
        self.menu_edit_remove_support.setText(_translate("MainWindow", "Support", None))
        self.menu_edit_remove_all.setText(_translate("MainWindow", "All", None))
        self.menu_help_contact.setText(_translate("MainWindow", "Contact Support", None))
        self.menu_settings_manage.setText(_translate("MainWindow", "Manage data", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

